-- Generated by matugen from ~/toph-nixos/home/matugen/hyprland-colors.lua.
-- Don't edit this copy: `toph-theme` rewrites it on every colour change.
-- Source colour: {{colors.source_color.default.hex}}
return {
    source           = "{{colors.source_color.default.hex_stripped}}",
    primary          = "{{colors.primary.default.hex_stripped}}",
    primaryContainer = "{{colors.primary_container.default.hex_stripped}}",
    surface          = "{{colors.surface.default.hex_stripped}}",
    outlineVariant   = "{{colors.outline_variant.default.hex_stripped}}",
    shadow           = "{{colors.shadow.default.hex_stripped}}",
}
